FROM rayproject/ray:2.48.0.2c63f6-py39-cpu
USER root

RUN apt-get update
RUN apt-get update && apt-get install -y \
    vim \
    net-tools \
    lrzsz \
    sox \
    libsox-dev \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN conda create -y -n AudioPipeline python=3.9 && \
    conda install -n AudioPipeline -y -c conda-forge \
    ffmpeg \
    hdbscan
    
RUN conda install -n AudioPipeline pytorch=2.5.0 torchvision=0.20.0 torchaudio=2.5.0 pytorch-cuda=12.1 -c pytorch -c nvidia -y

RUN mkdir -p /home/oicq/audio_preprocess
RUN pwd
COPY . /home/oicq/audio_preprocess
WORKDIR  /home/oicq/audio_preprocess

RUN echo "source activate AudioPipeline" >> ~/.bashrc
RUN conda run -n AudioPipeline pip install -r requirements.txt
RUN conda run -n AudioPipeline pip install onnxruntime-gpu==1.19.2
RUN conda run -n AudioPipeline python main.py --prepare_env 1

# ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["./scripts/start_ray.sh", "auto"]
